apiVersion: v1
description: A Fluentd Elasticsearch Helm chart for Kubernetes.
icon: https://raw.githubusercontent.com/fluent/fluentd-docs/master/public/logo/Fluentd_square.png
name: fluentd
version: 0.1.0
appVersion: v2.3.1
home: https://www.fluentd.org/
sources:
- https://www.fluentd.org/
maintainers:
- name: dstorck
  email: deirdre.storck@gmail.com