apiVersion: v1
kind: Secret
metadata: 
  name: {{ template "fluentd.fullname" . }}-auth
  labels:
    app: {{ template "fluentd.name" . }}
    chart: {{ template "namewithversion" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
stringData:
    awsSecKey: "{{ .Values.awsSecKey }}"
    awsKeyId: "{{ .Values.awsKeyId }}"